services:
  db:
    image: mysql:8.0
    container_name: cool-mysql
    restart: unless-stopped

    # Port mapping
    ports:
      - "3307:3306"

    # Environment variables
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    # Mount initialization scripts and persist data
    volumes:
      # Persistent data storage for MYSQL
      - db_data:/var/lib/mysql 
      # Initialize schema on first run
      - ./initdb:/docker-entrypoint-initdb.d 

  # OpenSSL service for RSA key generation
  # Run service with: docker-compose -f database/docker-compose.yaml --profile openssl run --rm rsakeys              
  rsakeys:
    image: alpine/openssl:latest
    container_name: cool-openssl
    entrypoint: ["sh", "-c"]
    working_dir: /certs
    volumes:
      - ../back-end/resources/certs:/certs
    profiles:
      - openssl
    command: |
      "if [ ! -f /certs/private.pem ]; then
        echo 'Generating RSA keys...' &&
        openssl genrsa -out /certs/keypair.pem 2048 &&
        openssl rsa -in /certs/keypair.pem -pubout -out /certs/public.pem &&
        openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in /certs/keypair.pem -out /certs/private.pem &&
        rm /certs/keypair.pem &&
        echo 'Keys generated successfully!'
      else
        echo 'No generation, RSA keys already exist!'
      fi"

# Declares the named volume for MySQL data persistence
volumes:
  db_data: